name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - run: terraform init
        working-directory: terraform-eks-mock
      - run: terraform validate
        working-directory: terraform-eks-mock
      - run: terraform plan -out=tfplan
        working-directory: terraform-eks-mock

  kind-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind && sudo mv ./kind /usr/local/bin/kind
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Create kind cluster
        run: kind create cluster --config=kind-k8s-cluster/kind-config.yaml
      - name: Deploy app via Helm
        run: |
          helm install hello-release kind-k8s-cluster/helm-chart
      - name: Deploy monitoring via Helm
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/prometheus -f kind-k8s-cluster/monitoring/prometheus-values.yaml
          helm install grafana grafana/grafana -f kind-k8s-cluster/monitoring/grafana-values.yaml